server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:shared
  profiles:
     active: native 
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/